// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:ParquetViewer.Engine.ParquetNET.ParquetEngine.ReadRowsAsync(System.Collections.Generic.List{System.String},System.Int32,System.Int32,System.IProgress{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Func{System.Boolean,System.Data.DataTable}}")]
[assembly: SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:ParquetViewer.Engine.ParquetNET.ParquetEngine.ProcessRowGroup(ParquetViewer.Engine.DataTableLite,Parquet.ParquetRowGroupReader,System.Int64,System.Int64,System.Threading.CancellationToken,System.IProgress{System.Int32})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:ParquetViewer.Engine.ParquetNET.ParquetEngine.ReadListField(ParquetViewer.Engine.DataTableLite,Parquet.ParquetRowGroupReader,System.Int32,ParquetViewer.Engine.ParquetNET.ParquetSchemaElement,System.Int32,System.Int64,System.Int64,System.Boolean,System.Threading.CancellationToken,System.IProgress{System.Int32})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:ParquetViewer.Engine.ParquetNET.ParquetEngine.ReadStructField(ParquetViewer.Engine.DataTableLite,Parquet.ParquetRowGroupReader,System.Int32,ParquetViewer.Engine.ParquetNET.ParquetSchemaElement,System.Int64,System.Int64,System.Boolean,System.Threading.CancellationToken,System.IProgress{System.Int32})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:ParquetViewer.Engine.ParquetNET.ListValueBuilder.GetRowRanges~System.Collections.Generic.IEnumerable{System.Range}")]
[assembly: SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:ParquetViewer.Engine.ParquetNET.ParquetEngine.ReadRowsAsync(System.Collections.Generic.List{System.String},System.Int32,System.Int32,System.IProgress{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Func{System.Boolean,System.Data.DataTable}}")]