//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParquetViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParquetViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string CancelInitiatedLabelText {
            get {
                return ResourceManager.GetString("CancelInitiatedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t go back.
        /// </summary>
        internal static string CantGoBackLinkButtonText {
            get {
                return ResourceManager.GetString("CantGoBackLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as WHERE....
        /// </summary>
        internal static string CopyAsWhereConditionText {
            get {
                return ResourceManager.GetString("CopyAsWhereConditionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyToClipboardText {
            get {
                return ResourceManager.GetString("CopyToClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy with headers.
        /// </summary>
        internal static string CopyToClipboardWithHeadersText {
            get {
                return ResourceManager.GetString("CopyToClipboardWithHeadersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table script copied to clipboard!.
        /// </summary>
        internal static string CreateTableScriptCopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("CreateTableScriptCopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some fields first to get the SQL script.
        /// </summary>
        internal static string CreateTableScriptFailedWithNoFieldsMessage {
            get {
                return ResourceManager.GetString("CreateTableScriptFailedWithNoFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string DecimalFormatting {
            get {
                return ResourceManager.GetString("DecimalFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        internal static string DecimalScientificFormatting {
            get {
                return ResourceManager.GetString("DecimalScientificFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All (Count: {0}).
        /// </summary>
        internal static string DeselectAllCheckmarkTextFormat {
            get {
                return ResourceManager.GetString("DeselectAllCheckmarkTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        internal static string DimensionsText {
            get {
                return ResourceManager.GetString("DimensionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings.
        /// </summary>
        internal static string DotNetDateFormatHelpUrl {
            get {
                return ResourceManager.GetString("DotNetDateFormatHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export has been cancelled.
        /// </summary>
        internal static string ExportCancelledMessage {
            get {
                return ResourceManager.GetString("ExportCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Cancelled.
        /// </summary>
        internal static string ExportCancelledTitle {
            get {
                return ResourceManager.GetString("ExportCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Data.
        /// </summary>
        internal static string ExportingDataLabelText {
            get {
                return ResourceManager.GetString("ExportingDataLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful!
        ///
        ///File size: {0} MB.
        /// </summary>
        internal static string ExportSuccessfulMessageFormat {
            get {
                return ResourceManager.GetString("ExportSuccessfulMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ExportSuccessfulTitle {
            get {
                return ResourceManager.GetString("ExportSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved to {0}.
        /// </summary>
        internal static string ImageSavedToDiskMessage {
            get {
                return ResourceManager.GetString("ImageSavedToDiskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save complete.
        /// </summary>
        internal static string ImageSavedToDiskTitle {
            get {
                return ResourceManager.GetString("ImageSavedToDiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing.
        /// </summary>
        internal static string IndexingDataLabelText {
            get {
                return ResourceManager.GetString("IndexingDataLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid date format.
        /// </summary>
        internal static string InvalidDateFormatErrorText {
            get {
                return ResourceManager.GetString("InvalidDateFormatErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the language requires an app restart. Would you like to continue?.
        /// </summary>
        internal static string LanguageChangeConfirmationMessage {
            get {
                return ResourceManager.GetString("LanguageChangeConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart ParquetViewer?.
        /// </summary>
        internal static string LanguageChangeConfirmationTitle {
            get {
                return ResourceManager.GetString("LanguageChangeConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string LoadedRecordCountRangeFormat {
            get {
                return ResourceManager.GetString("LoadedRecordCountRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data.
        /// </summary>
        internal static string LoadingDataLabelText {
            get {
                return ResourceManager.GetString("LoadingDataLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        internal static string MainWindowOpenFileTitleFormat {
            get {
                return ResourceManager.GetString("MainWindowOpenFileTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: {0}.
        /// </summary>
        internal static string MainWindowOpenFolderTitleFormat {
            get {
                return ResourceManager.GetString("MainWindowOpenFolderTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata successfully exported to: {0}.
        /// </summary>
        internal static string MetadataSuccessfullyExportedToFileMessageFormat {
            get {
                return ResourceManager.GetString("MetadataSuccessfullyExportedToFileMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete.
        /// </summary>
        internal static string MetadataSuccessfullyExportedToFileMessageTitle {
            get {
                return ResourceManager.GetString("MetadataSuccessfullyExportedToFileMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicyLabelText {
            get {
                return ResourceManager.GetString("PrivacyPolicyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL CHECK: 
        ///    WHERE field_name IS NULL
        ///    WHERE field_name IS NOT NULL
        ///DATETIME:   
        ///    WHERE field_name &gt;= #2000-12-31#
        ///    WHERE field_name = #2000-01-13 01:00:00#
        ///NUMERIC:
        ///    WHERE field_name &lt;= 123.4
        ///    WHERE (field1 * field2) / 100 &gt; 0.1
        ///STRING:
        ///    WHERE field_name LIKE &apos;%value%&apos; 
        ///    WHERE field_name = &apos;equals value&apos;
        ///    WHERE field_name &lt;&gt; &apos;not equals&apos;
        ///IN CHECK:
        ///    WHERE field_name IN (value1, value2)
        ///    WHERE field_name NOT IN (value3, value4)
        ///MULTIPLE CONDITIONS: 
        ///    WHER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuerySyntaxHelpText {
            get {
                return ResourceManager.GetString("QuerySyntaxHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Query Syntax Examples.
        /// </summary>
        internal static string QuerySyntaxHelpTitle {
            get {
                return ResourceManager.GetString("QuerySyntaxHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records will be exported.
        /// </summary>
        internal static string RecordsToBeExportedTitleFormat {
            get {
                return ResourceManager.GetString("RecordsToBeExportedTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image as {0}.
        /// </summary>
        internal static string SaveImageAsButtonText {
            get {
                return ResourceManager.GetString("SaveImageAsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as {0}.
        /// </summary>
        internal static string SaveImageToFileButtonTextFormat {
            get {
                return ResourceManager.GetString("SaveImageToFileButtonTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save raw metadata.
        /// </summary>
        internal static string SaveRawMetadataToFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveRawMetadataToFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All (Count: {0}).
        /// </summary>
        internal static string SelectAllCheckmarkTextFormat {
            get {
                return ResourceManager.GetString("SelectAllCheckmarkTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum {0} characters per cell are supported for {1} files.
        ///
        ///Would you like to switch to a {2} file instead?.
        /// </summary>
        internal static string SwitchFromXlsToXlsxMessageFormat {
            get {
                return ResourceManager.GetString("SwitchFromXlsToXlsxMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data too large - Switch export type?.
        /// </summary>
        internal static string SwitchFromXlsToXlsxMessageTitle {
            get {
                return ResourceManager.GetString("SwitchFromXlsToXlsxMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Thrift metadata copied to clipboard..
        /// </summary>
        internal static string ThriftMetadataCopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("ThriftMetadataCopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many fields: {0}.
        /// </summary>
        internal static string TooManyFieldsErrorFormat {
            get {
                return ResourceManager.GetString("TooManyFieldsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported: {0}.
        /// </summary>
        internal static string UnsupportedFieldCountTextFormat {
            get {
                return ResourceManager.GetString("UnsupportedFieldCountTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unsupported).
        /// </summary>
        internal static string UnsupportedFieldText {
            get {
                return ResourceManager.GetString("UnsupportedFieldText", resourceCulture);
            }
        }
    }
}
